staging:
  user-workflow:
    workflow-name: "liquidmind-staging"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.staging.json"
    secrets-path: ""

production:
  user-workflow:
    workflow-name: "liquidmind-production"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.production.json"
    secrets-path: ""
